-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS RaakaAine CASCADE;
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS KayttajaRaakaAine CASCADE;
DROP TABLE IF EXISTS RaakaAineResepti CASCADE;