-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Chef CASCADE;
DROP TABLE IF EXISTS Food CASCADE;
DROP TABLE IF EXISTS Recipe CASCADE;
DROP TABLE IF EXISTS ChefFood CASCADE;
DROP TABLE IF EXISTS ChefRecipe CASCADE;
DROP TABLE IF EXISTS RecipeFood CASCADE;
