-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS RaakaAine CASCADE;
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS ChefFood CASCADE;
DROP TABLE IF EXISTS ChefRecipe CASCADE;
DROP TABLE IF EXISTS RaakaAineResepti CASCADE;
